In [56]:
import pandas as pd

In [57]:
df = pd.read_csv("autodata.csv")

In [58]:
df

,Unnamed: 0,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,0,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,13495.0,11.190476,Low,0,1
1,1,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,16500.0,11.190476,Low,0,1
2,2,1,122,alfa-romero,std,two,hatchback,rwd,front,94.5,...,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,3,2,164,audi,std,four,sedan,fwd,front,99.8,...,10.0,102.0,5500.0,24,30,13950.0,9.791667,Low,0,1
4,4,2,164,audi,std,four,sedan,4wd,front,99.4,...,8.0,115.0,5500.0,18,22,17450.0,13.055556,Low,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,196,-1,95,volvo,std,four,sedan,rwd,front,109.1,...,9.5,114.0,5400.0,23,28,16845.0,10.217391,Low,0,1
197,197,-1,95,volvo,turbo,four,sedan,rwd,front,109.1,...,8.7,160.0,5300.0,19,25,19045.0,12.368421,Medium,0,1
198,198,-1,95,volvo,std,four,sedan,rwd,front,109.1,...,8.8,134.0,5500.0,18,23,21485.0,13.055556,Medium,0,1
199,199,-1,95,volvo,turbo,four,sedan,rwd,front,109.1,...,23.0,106.0,4800.0,26,27,22470.0,9.038462,Low,1,0
200,200,-1,95,volvo,turbo,four,sedan,rwd,front,109.1,...,9.5,114.0,5400.0,19,25,22625.0,12.368421,Low,0,1

In [59]:
df.isnull()

,Unnamed: 0,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
197,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
198,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
199,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
200,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [60]:
df.isnull().sum()

Unnamed: 0           0
symboling            0
normalized-losses    0
make                 0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               4
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                0
city-L/100km         0
horsepower-binned    2
diesel               0
gas                  0
dtype: int64

In [61]:
df.notnull()

,Unnamed: 0,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
197,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
198,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
199,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
200,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [62]:
df.notnull().sum()

Unnamed: 0           201
symboling            201
normalized-losses    201
make                 201
aspiration           201
num-of-doors         201
body-style           201
drive-wheels         201
engine-location      201
wheel-base           201
length               201
width                201
height               201
curb-weight          201
engine-type          201
num-of-cylinders     201
engine-size          201
fuel-system          201
bore                 201
stroke               197
compression-ratio    201
horsepower           199
peak-rpm             199
city-mpg             201
highway-mpg          201
price                201
city-L/100km         201
horsepower-binned    199
diesel               201
gas                  201
dtype: int64

In [63]:
df.describe()

,Unnamed: 0,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
count,201.000000,201.000000,201.00000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,197.000000,201.000000,199.000000,199.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000
mean,100.000000,0.840796,122.00000,98.797015,0.837102,0.915126,53.766667,2555.666667,126.875622,3.330692,3.256904,10.164279,103.396985,5117.587940,25.179104,30.686567,13207.129353,9.944145,0.099502,0.900498
std,58.167861,1.254802,31.99625,6.066366,0.059213,0.029187,2.447822,517.296727,41.546834,0.268072,0.319256,4.004965,37.553843,480.521824,6.423220,6.815150,7947.066342,2.534599,0.300083,0.300083
min,0.000000,-2.000000,65.00000,86.600000,0.678039,0.837500,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000,4.795918,0.000000,0.000000
25%,50.000000,0.000000,101.00000,94.500000,0.801538,0.890278,52.000000,2169.000000,98.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7775.000000,7.833333,0.000000,1.000000
50%,100.000000,1.000000,122.00000,97.000000,0.832292,0.909722,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000,9.791667,0.000000,1.000000
75%,150.000000,2.000000,137.00000,102.400000,0.881788,0.925000,55.500000,2926.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16500.000000,12.368421,0.000000,1.000000
max,200.000000,3.000000,256.00000,120.900000,1.000000,1.000000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,262.000000,6600.000000,49.000000,54.000000,45400.000000,18.076923,1.000000,1.000000

In [64]:
df.size

6030

In [65]:
df.ndim

2

In [66]:
df.shape

(201, 30)

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         201 non-null    int64
 1   symboling          201 non-null    int64
 2   normalized-losses  201 non-null    int64
 3   make               201 non-null    object
 4   aspiration         201 non-null    object
 5   num-of-doors       201 non-null    object
 6   body-style         201 non-null    object
 7   drive-wheels       201 non-null    object
 8   engine-location    201 non-null    object
 9   wheel-base         201 non-null    float64
 10  length             201 non-null    float64
 11  width              201 non-null    float64
 12  height             201 non-null    float64
 13  curb-weight        201 non-null    int64
 14  engine-type        201 non-null    object
 15  num-of-cylinders   201 non-null    object
 16  engine-size        201 non-null    int64
 17  fuel-system        201 non-null    object
 18  bore               201 non-null    float64
 19  stroke             197 non-null    float64
 20  compression-ratio  201 non-null    float64
 21  horsepower         199 non-null    float64
 22  peak-rpm           199 non-null    float64
 23  city-mpg           201 non-null    int64
 24  highway-mpg        201 non-null    int64
 25  price              201 non-null    float64
 26  city-L/100km       201 non-null    float64
 27  horsepower-binned  199 non-null    object
 28  diesel             201 non-null    int64
 29  gas                201 non-null    int64
dtypes: float64(11), int64(9), object(10)
memory usage: 47.2+ KB

In [77]:
df = df.dropna()

In [78]:
df

,Unnamed: 0,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,0.0,3.0,122.0,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21.0,27.0,13495.0,11.190476,Low,0.0,1.0
1,1.0,3.0,122.0,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21.0,27.0,16500.0,11.190476,Low,0.0,1.0
2,2.0,1.0,122.0,alfa-romero,std,two,hatchback,rwd,front,94.5,...,9.0,154.0,5000.0,19.0,26.0,16500.0,12.368421,Medium,0.0,1.0
3,3.0,2.0,164.0,audi,std,four,sedan,fwd,front,99.8,...,10.0,102.0,5500.0,24.0,30.0,13950.0,9.791667,Low,0.0,1.0
4,4.0,2.0,164.0,audi,std,four,sedan,4wd,front,99.4,...,8.0,115.0,5500.0,18.0,22.0,17450.0,13.055556,Low,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,196.0,-1.0,95.0,volvo,std,four,sedan,rwd,front,109.1,...,9.5,114.0,5400.0,23.0,28.0,16845.0,10.217391,Low,0.0,1.0
197,197.0,-1.0,95.0,volvo,turbo,four,sedan,rwd,front,109.1,...,8.7,160.0,5300.0,19.0,25.0,19045.0,12.368421,Medium,0.0,1.0
198,198.0,-1.0,95.0,volvo,std,four,sedan,rwd,front,109.1,...,8.8,134.0,5500.0,18.0,23.0,21485.0,13.055556,Medium,0.0,1.0
199,199.0,-1.0,95.0,volvo,turbo,four,sedan,rwd,front,109.1,...,23.0,106.0,4800.0,26.0,27.0,22470.0,9.038462,Low,1.0,0.0
200,200.0,-1.0,95.0,volvo,turbo,four,sedan,rwd,front,109.1,...,9.5,114.0,5400.0,19.0,25.0,22625.0,12.368421,Low,0.0,1.0

In [97]:
df.loc[:, 'horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')
df = df.dropna(subset=['horsepower'])
df['horsepower'] = df['horsepower'].astype(int)

In [98]:
df

,Unnamed: 0,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,0.0,3.0,122.0,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111,5000.0,21.0,27.0,13495.0,11.190476,Low,0.0,1.0
1,1.0,3.0,122.0,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111,5000.0,21.0,27.0,16500.0,11.190476,Low,0.0,1.0
2,2.0,1.0,122.0,alfa-romero,std,two,hatchback,rwd,front,94.5,...,9.0,154,5000.0,19.0,26.0,16500.0,12.368421,Medium,0.0,1.0
3,3.0,2.0,164.0,audi,std,four,sedan,fwd,front,99.8,...,10.0,102,5500.0,24.0,30.0,13950.0,9.791667,Low,0.0,1.0
4,4.0,2.0,164.0,audi,std,four,sedan,4wd,front,99.4,...,8.0,115,5500.0,18.0,22.0,17450.0,13.055556,Low,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,196.0,-1.0,95.0,volvo,std,four,sedan,rwd,front,109.1,...,9.5,114,5400.0,23.0,28.0,16845.0,10.217391,Low,0.0,1.0
197,197.0,-1.0,95.0,volvo,turbo,four,sedan,rwd,front,109.1,...,8.7,160,5300.0,19.0,25.0,19045.0,12.368421,Medium,0.0,1.0
198,198.0,-1.0,95.0,volvo,std,four,sedan,rwd,front,109.1,...,8.8,134,5500.0,18.0,23.0,21485.0,13.055556,Medium,0.0,1.0
199,199.0,-1.0,95.0,volvo,turbo,four,sedan,rwd,front,109.1,...,23.0,106,4800.0,26.0,27.0,22470.0,9.038462,Low,1.0,0.0
200,200.0,-1.0,95.0,volvo,turbo,four,sedan,rwd,front,109.1,...,9.5,114,5400.0,19.0,25.0,22625.0,12.368421,Low,0.0,1.0

In [20]:
print(df["horsepower"])

0      111
1      111
2      154
3      102
4      115
      ...
196    114
197    160
198    134
199    106
200    114
Name: horsepower, Length: 195, dtype: int64

In [21]:
print(df.columns)

Index(['Unnamed: 0', 'symboling', 'normalized-losses', 'make', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price', 'city-L/100km', 'horsepower-binned', 'diesel',
       'gas'],
      dtype='object')

In [33]:
df.loc[:, "aspiration"] = df["aspiration"].replace({"std": 0, "turbo": 1}).astype(int)

In [34]:
print(df["aspiration"])

0      0
1      0
2      0
3      0
4      0
      ..
196    0
197    1
198    0
199    1
200    1
Name: aspiration, Length: 195, dtype: int64