In [19]:
import pandas as pd

In [21]:
df = pd.read_csv("Iris.csv")

In [22]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [23]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [26]:
df["SepalLengthCm"].describe()

count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000
Name: SepalLengthCm, dtype: float64

In [27]:
df.groupby("Species").describe().sum()

Id             count    150.000000
               mean     226.500000
               std       43.732139
               min      153.000000
               25%      189.750000
               50%      226.500000
               75%      263.250000
               max      300.000000
SepalLengthCm  count    150.000000
               mean      17.530000
               std        1.504540
               min       14.100000
               25%       16.625000
               50%       17.400000
               75%       18.400000
               max       20.700000
SepalWidthCm   count    150.000000
               mean       9.162000
               std        1.017319
               min        6.500000
               25%        8.450000
               50%        9.200000
               75%        9.850000
               max       11.600000
PetalLengthCm  count    150.000000
               mean      11.276000
               std        1.195317
               min        8.500000
               25%       10.500000
               50%       11.400000
               75%       12.050000
               max       13.900000
PetalWidthCm   count    150.000000
               mean       3.596000
               std        0.579612
               min        2.500000
               25%        3.200000
               50%        3.500000
               75%        4.100000
               max        4.900000
dtype: float64

In [31]:
df.drop(columns=['Id'], inplace=True)

In [32]:
grouped_stats = df.groupby('Species').agg(['mean', 'median', 'min', 'max', 'std'])
print("Grouped Summary Statistics:\n")
print(grouped_stats)

Grouped Summary Statistics:

                SepalLengthCm                            SepalWidthCm         \
                         mean median  min  max       std         mean median
Species
Iris-setosa             5.006    5.0  4.3  5.8  0.352490        3.418    3.4
Iris-versicolor         5.936    5.9  4.9  7.0  0.516171        2.770    2.8
Iris-virginica          6.588    6.5  4.9  7.9  0.635880        2.974    3.0

                                    PetalLengthCm                             \
                 min  max       std          mean median  min  max       std
Species
Iris-setosa      2.3  4.4  0.381024         1.464   1.50  1.0  1.9  0.173511
Iris-versicolor  2.0  3.4  0.313798         4.260   4.35  3.0  5.1  0.469911
Iris-virginica   2.2  3.8  0.322497         5.552   5.55  4.5  6.9  0.551895

                PetalWidthCm
                        mean median  min  max       std
Species
Iris-setosa            0.244    0.2  0.1  0.6  0.107210
Iris-versicolor        1.326    1.3  1.0  1.8  0.197753
Iris-virginica         2.026    2.0  1.4  2.5  0.274650

In [33]:
species_counts = df['Species'].value_counts().to_dict()
print("\nNumber of samples per species (as a list):")
species_count_list = list(species_counts.values())
print(species_count_list)

Number of samples per species (as a list):
[50, 50, 50]

In [36]:
print("\nDescriptive statistics for each species:")
for species in df['Species'].unique():
    print(f"\nStatistics for {species}:")
    print(df[df['Species'] == species].describe(percentiles=[.25, .5, .75]))

Descriptive statistics for each species:

Statistics for Iris-setosa:
       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count       50.00000     50.000000      50.000000      50.00000
mean         5.00600      3.418000       1.464000       0.24400
std          0.35249      0.381024       0.173511       0.10721
min          4.30000      2.300000       1.000000       0.10000
25%          4.80000      3.125000       1.400000       0.20000
50%          5.00000      3.400000       1.500000       0.20000
75%          5.20000      3.675000       1.575000       0.30000
max          5.80000      4.400000       1.900000       0.60000

Statistics for Iris-versicolor:
       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count      50.000000     50.000000      50.000000     50.000000
mean        5.936000      2.770000       4.260000      1.326000
std         0.516171      0.313798       0.469911      0.197753
min         4.900000      2.000000       3.000000      1.000000
25%         5.600000      2.525000       4.000000      1.200000
50%         5.900000      2.800000       4.350000      1.300000
75%         6.300000      3.000000       4.600000      1.500000
max         7.000000      3.400000       5.100000      1.800000

Statistics for Iris-virginica:
       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count       50.00000     50.000000      50.000000      50.00000
mean         6.58800      2.974000       5.552000       2.02600
std          0.63588      0.322497       0.551895       0.27465
min          4.90000      2.200000       4.500000       1.40000
25%          6.22500      2.800000       5.100000       1.80000
50%          6.50000      3.000000       5.550000       2.00000
75%          6.90000      3.175000       5.875000       2.30000
max          7.90000      3.800000       6.900000       2.50000